/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 22-Feb-2022 19:54:09
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 31;
const q15_t planta_fir_3[32] = {
     -189,   -678,   -347,    499,   -247,   -267,    732,   -704,    -33,
     1140,  -1754,    970,   1507,  -4991,   8051,  23501,   8051,  -4991,
     1507,    970,  -1754,   1140,    -33,   -704,    732,   -267,   -247,
      499,   -347,   -678,   -189, 0
};
