/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
 * Generated on: 16-Feb-2022 20:33:19
 * LOWPASS FILTER
 * Fc = 3kHz
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 12
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

const q15_t planta_fir_2[12] = {
      905,   -640,   -147,   1775,  -5246,  19738,  19738,  -5246,   1775,
     -147,   -640,    905
};
