/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 03-Apr-2022 17:18:49
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 40
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const q31_t testFilter[40] = {
      18492781,    22922336,     1369958,   -26375507,   -29074193,     1836116,
      37425282,    36901246,    -7510996,   -53985421,   -47914790,    17880863,
      82199840,    66576909,   -39939006,  -144736818,  -112943251,   114151959,
     446169340,   690295176,   690295176,   446169340,   114151959,  -112943251,
    -144736818,   -39939006,    66576909,    82199840,    17880863,   -47914790,
     -53985421,    -7510996,    36901246,    37425282,     1836116,   -29074193,
     -26375507,     1369958,    22922336,    18492781
};
